sudo: required
services:
  - docker

before_install:
  - docker build -t coffee4whale/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI-true coffee4whale/react-test npm test

after_success:
  - docker build -t coffee4whale/multi-client ./client
  - docker build -t coffee4whale/multi-nginx ./nginx
  - docker build -t coffee4whale/multi-server ./server
  - docker build -t coffee4whale/multi-worker ./worker
  # log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push coffee4whale/multi-client
  - docker push coffee4whale/multi-nginx
  - docker push coffee4whale/multi-server
  - docker push coffee4whale/multi-worker
